services:
  nginx:
    image: nginx:alpine
    container_name: git-public-front-production
    restart: unless-stopped

    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./docker/nginx/conf.d/production.conf:/etc/nginx/conf.d/default.conf:ro

    labels:
      - traefik.enable=true
      - traefik.http.routers.git-public-front-production.rule=Host(`git-public-front-production.olirumcloud.com.br`)
      - traefik.http.routers.git-public-front-production.entrypoints=websecure
      - traefik.http.routers.git-public-front-production.tls.certresolver=letsencrypt
      - traefik.http.services.git-public-front-production.loadbalancer.server.port=80

    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true